name: Pipeline para Consultar de CEP - CI/CD

on:
  push:
    branches:
      - main

jobs:
  consulta-cep:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar o repositório
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Instalar dependências
      run: npm install

    - name: Executar script de consulta ao ViaCep
      run: node caminho/do/seu/script.js
